version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document-api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OCR_ENABLED=${OCR_ENABLED}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/').read()\""]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: document-frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://api:8000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started

networks:
  default:
    name: document-network
