services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: shipment-backend
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs
      - temp_files:/app/temp
    networks:
      - shipment-network
    expose:
      - "8000"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: shipment-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - shipment-network

networks:
  shipment-network:
    driver: bridge

volumes:
  temp_files:
  logs:
